
version: "3.8"

services:

  #  MongoDB
  mongo:
    image: mongo
    ports:
      - "27018:27017"

  #  App
  comment-service-blog-platform:
    depends_on:
      - mongo
    image: comment-service-blog-platform-image
    ports:
      - "8082:8082"