server:
  port: 8082

spring:
  application:
    name: comment-service
  data:
    mongodb:
#      uri: mongodb://localhost:27017/comment-service-blog-platform
      uri: mongodb://mongo:27017/comment-service-blog-platform # for docker
  graphql:
    graphiql:
      enabled: true
